### PR TITLE
Update gradle to latest stable version

### PR DESCRIPTION
**Pull request by kanvuduc**
Update gradle settings for v26 ready.
Update Android Support version to v25.4.0

Answered issue #42: It just works!

### CODE REVIEW

**Comment by ittianyu** [comment]
I know. But I can't access https://maven.google.com even with vpn.
Let me create a new branch.

**Comment by ittianyu** [comment]
Can you help me test version 26.0.0 ?

**Comment by ittianyu** [comment]
Can you try version 1.2.3 ?

**Comment by kanvuduc** [comment]
> Can you help me test version 26.0.0 ?
Yes, I did before creating pull request.

**Pull request closed without merging**
