### PR TITLE
apply sdk version 28 with android x.

### PR DESCRIPTION
**Pull request by jcsla**

### CODE REVIEW

**Comment by searchy2** [comment]
Please merge this PR, thanks!

**Comment by jcsla** [comment]
Thanks.
@searchy2 @ittianyu

**Comment by searchy2** [comment]
@jcsla Thank you so much for the fix! You did all the work and I couldn't have used this great library without it. Amazing :)

**Comment by searchy2** [comment]
@ittianyu This library is really great because it works with the new Android Jetpack components. Thank you for making it and sharing!

**Comment by jcsla** [comment]
@searchy2 👍

**Comment by ubuntudroid** [comment]
@ittianyu has the merged stuff been removed again from master? Seems everything since the last release is gone. 🤔

**Pull request merged**
